// import Head from 'next/head'
// import Image from "next/image";
import Layout from "../layouts/landing";

import HomeHero from "../components/home/hero";
import PopularCourses from "../components/home/popularCourses";
import ExpandCareer from "../components/home/expandCareer";
import PopularVideos from "../components/home/popularVideos";
import Certifications from "../components/home/certifications";
import Companies from "../components/home/companies";
import Article from "../components/home/article";
import Reviews from "../components/home/reviews";
import Outreach from "../components/home/outreach";
import Outro from "../components/home/outro";

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <HomeHero />
      <PopularCourses />
      <ExpandCareer />
      <PopularVideos />
      <Certifications
        lead="GET UP TO SPEED"
        heading="Certifications to uplift tech your skill"
      />
      <Companies />
      <Article btnText="SEE ALL INSIGHTS" />
      <Reviews />
      <Outreach />
      <Outro
        outroText="Keep yourself ahead by keeping up on your dream"
        outroBtn="TRY FOR FREE"
        outroLink="/register"
      />
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
